const PROJECTS = {
  leo: {
    type: "detail",
    title: "Lemon Orange Sparkling",
    desc: ["상큼한 레몬과 오렌지의 만남", "상쾌한 스파클링 워터"],
    tags: ["Detail Page", "Responsive", "Design", "Publishing"],
    year: "2026",
    period: "3 Weeks",
    role: "UI/UX Design, Visual Design",
    tools: ["Figma", "Photoshop", "Illustrator"],
    overview:
      "상큼한 레몬과 오렌지의 조합으로 일상 속 상쾌함을 전달하는 스파클링 워터 상세페이지입니다.",
    features: [
      { title: "상큼한 과일의 조합", desc: "레몬과 오렌지의 상큼한 맛을 시각적으로 표현" },
      { title: "짜릿한 스파클링", desc: "톡 쏘는 탄산으로 청량감 극대화" },
      { title: "자연 유래 원료", desc: "안전하고 신뢰감 있는 원료 강조" },
      { title: "간편한 수분 보충", desc: "언제 어디서나 가볍게 즐기는 제품 경험" },
    ],
    concept:
      "여름 바다의 청량함과 과일의 상큼함을 시각적으로 전달하여 제품의 특징을 직관적으로 표현했습니다.",
    colors: ["#FFD54D", "#FF9800", "#87CEFA", "#FFFFFF", "#333333"],
    keywords: ["Fresh", "Sparkling", "Clean", "Natural", "Bright"],
    zoom: [
      { title: "메인 비주얼", desc: "시원한 바다와 제품으로 청량감을 강조" },
      { title: "리뷰 & 평점", desc: "신뢰도를 높이는 평점과 사용자 리뷰 강조" },
      { title: "제품 특징", desc: "핵심 특징을 아이콘과 함께 직관적으로 전달" },
      { title: "활용 이미지", desc: "다양한 활용 컷으로 제품의 매력 어필" },
    ],
  },
  tumbler: {
    type: "detail",
    title: "Tumbler",
    desc: ["일상을 채우는 감각적인 텀블러", "보온·보냉과 스타일을 동시에"],
    tags: ["Detail Page", "Responsive", "Design"],
    year: "2026",
    period: "2 Weeks",
    role: "UI/UX Design, Visual Design",
    tools: ["Figma", "Photoshop"],
    overview: "프리미엄 텀블러의 기능과 디자인을 강조하는 상세페이지입니다.",
    features: [
      { title: "제품 디테일 강조", desc: "소재와 마감 품질을 클로즈업으로 표현" },
      { title: "라이프스타일 연출", desc: "일상 속 사용 장면으로 공감대 형성" },
      { title: "스펙 비교", desc: "용량·보온 시간 등 핵심 정보를 한눈에" },
      { title: "구매 전환 설계", desc: "리뷰와 CTA로 구매 결정을 유도" },
    ],
    concept: "미니멀한 톤과 따뜻한 질감으로 프리미엄 감성을 전달했습니다.",
    colors: ["#2C2C2C", "#C4A882", "#F5F5F5", "#FFFFFF", "#8B7355"],
    keywords: ["Premium", "Minimal", "Warm", "Daily", "Quality"],
    zoom: [
      { title: "메인 비주얼", desc: "제품 실루엣과 브랜드 무드 강조" },
      { title: "소재 & 마감", desc: "스테인리스·실리콘 등 소재 디테일" },
      { title: "사용 시나리오", desc: "출근·운동·캠핑 등 활용 장면" },
      { title: "구매 정보", desc: "옵션·배송·리뷰 정보 정리" },
    ],
  },
  furniture: {
    type: "detail",
    title: "Furniture",
    desc: ["공간을 완성하는 모던 가구", "편안함과 미학의 균형"],
    tags: ["Detail Page", "Responsive", "Design"],
    year: "2026",
    period: "3 Weeks",
    role: "UI/UX Design, Visual Design",
    tools: ["Figma", "Photoshop"],
    overview: "모던 가구 브랜드의 감성과 제품 가치를 전달하는 상세페이지입니다.",
    features: [
      { title: "공간 연출", desc: "인테리어 컷으로 제품의 분위기 전달" },
      { title: "제품 라인업", desc: "소파·테이블 등 카테고리별 구성" },
      { title: "브랜드 스토리", desc: "제작 철학과 디자인 방향 소개" },
      { title: "구매 가이드", desc: "사이즈·소재 안내로 선택을 돕는 구조" },
    ],
    concept: "따뜻한 베이지 톤과 여백으로 고급스러운 주거 감성을 표현했습니다.",
    colors: ["#D4C4B0", "#8B7355", "#F5F1ED", "#FFFFFF", "#3D3D3D"],
    keywords: ["Modern", "Cozy", "Interior", "Natural", "Elegant"],
    zoom: [
      { title: "메인 비주얼", desc: "거실 공간과 소파의 조화" },
      { title: "브랜드 소개", desc: "스토어 무드와 핵심 가치" },
      { title: "인기 제품", desc: "베스트셀러 제품 하이라이트" },
      { title: "수치 강조", desc: "재구매율·평점 등 신뢰 지표" },
    ],
  },
  interior: {
    type: "detail",
    title: "Interior",
    desc: ["매일 아침 달라지는 욕실", "프리미엄 리모델링 서비스"],
    tags: ["Detail Page", "Responsive", "Design"],
    year: "2026",
    period: "3 Weeks",
    role: "UI/UX Design, Visual Design",
    tools: ["Figma", "Photoshop"],
    overview: "욕실 리모델링 서비스의 신뢰와 전문성을 전달하는 상세페이지입니다.",
    features: [
      { title: "시공 전·후 비교", desc: "변화를 한눈에 보여주는 비포/애프터" },
      { title: "패키지 안내", desc: "Basic·Standard·Premium 비교표" },
      { title: "시공 과정", desc: "6단계 프로세스로 투명성 확보" },
      { title: "고객 리뷰", desc: "실제 후기와 만족도 지표 강조" },
    ],
    concept: "따뜻한 베이지와 화이트로 깔끔하고 신뢰감 있는 분위기를 연출했습니다.",
    colors: ["#C4A882", "#F5F1ED", "#FFFFFF", "#3D3D3D", "#E8E0D8"],
    keywords: ["Clean", "Premium", "Trust", "Modern", "Warm"],
    zoom: [
      { title: "히어로", desc: "욕실 인테리어 메인 비주얼" },
      { title: "시공 비교", desc: "Before & After 시각화" },
      { title: "패키지", desc: "가격·구성 비교 테이블" },
      { title: "리뷰", desc: "고객 만족도와 후기" },
    ],
  },
  cauliflower: {
    type: "detail",
    title: "Cauliflower",
    desc: ["건강한 한 끼의 시작", "신선한 콜리플라워 도시락"],
    tags: ["Detail Page", "Responsive", "Design"],
    year: "2026",
    period: "2 Weeks",
    role: "UI/UX Design, Visual Design",
    tools: ["Figma", "Photoshop"],
    overview: "건강 식단 콜리플라워 도시락의 매력을 전달하는 상세페이지입니다.",
    features: [
      { title: "신선함 강조", desc: "원재료와 조리 과정을 시각적으로 표현" },
      { title: "영양 정보", desc: "칼로리·영양 성분을 명확하게 안내" },
      { title: "맛의 다양성", desc: "여러 메뉴 라인업 소개" },
      { title: "배송·보관", desc: "신선도 유지 방법과 배송 안내" },
    ],
    concept: "그린과 화이트 톤으로 건강하고 신선한 브랜드 이미지를 구축했습니다.",
    colors: ["#7CB342", "#FFFFFF", "#F1F8E9", "#33691E", "#FFEB3B"],
    keywords: ["Healthy", "Fresh", "Green", "Natural", "Clean"],
    zoom: [
      { title: "메인 비주얼", desc: "신선한 콜리플라워 제품 컷" },
      { title: "영양 성분", desc: "건강 정보 인포그래픽" },
      { title: "메뉴 라인업", desc: "다양한 맛 구성" },
      { title: "배송 안내", desc: "보관·배송 가이드" },
    ],
  },
  roomspray: {
    type: "detail",
    title: "Room Spray",
    desc: ["공간을 채우는 향기", "프리미엄 룸 스프레이"],
    tags: ["Detail Page", "Responsive", "Design"],
    year: "2026",
    period: "2 Weeks",
    role: "UI/UX Design, Visual Design",
    tools: ["Figma", "Photoshop"],
    overview: "감각적인 향과 공간 무드를 전달하는 룸 스프레이 상세페이지입니다.",
    features: [
      { title: "향 노트 소개", desc: "탑·미들·베이스 노트를 시각화" },
      { title: "공간 연출", desc: "침실·거실 등 사용 공간 제안" },
      { title: "성분 안내", desc: "천연 원료와 안전성 강조" },
      { title: "선물 패키지", desc: "기프트 세트 구성 소개" },
    ],
    concept: "소프트 파스텔과 플로럴 무드로 감성적인 브랜드 경험을 설계했습니다.",
    colors: ["#E8D5E8", "#C9A0DC", "#FFFFFF", "#F5F0F8", "#6B4C7A"],
    keywords: ["Scent", "Calm", "Floral", "Gift", "Mood"],
    zoom: [
      { title: "메인 비주얼", desc: "제품과 꽃잎 연출" },
      { title: "향 노트", desc: "향기 구성 설명" },
      { title: "사용 공간", desc: "인테리어와 함께하는 컷" },
      { title: "기프트", desc: "선물 패키지 구성" },
    ],
  },
  "crystal-glass": {
    type: "detail",
    title: "Crystal glass",
    desc: ["빛을 담는 크리스탈 글라스", "일상의 특별함"],
    tags: ["Detail Page", "Responsive", "Design"],
    year: "2026",
    period: "2 Weeks",
    role: "UI/UX Design, Visual Design",
    tools: ["Figma", "Photoshop"],
    overview: "크리스탈 글라스의 투명함과 고급스러움을 담은 상세페이지입니다.",
    features: [
      { title: "투명감 표현", desc: "빛 반사와 굴절을 살린 제품 촬영" },
      { title: "소재 스토리", desc: "크리스탈 제작 공정과 품질" },
      { title: "테이블 세팅", desc: "다이닝·홈 파티 연출" },
      { title: "라인업", desc: "와인·위스키·물잔 시리즈" },
    ],
    concept: "클리어 톤과 은은한 골드 포인트로 럭셔리 감성을 완성했습니다.",
    colors: ["#E8E8E8", "#C9B896", "#FFFFFF", "#1A1A1A", "#F0EDE8"],
    keywords: ["Crystal", "Luxury", "Clear", "Dining", "Elegant"],
    zoom: [
      { title: "메인 비주얼", desc: "빛나는 글라스 제품 컷" },
      { title: "소재", desc: "크리스탈 제작 스토리" },
      { title: "테이블", desc: "다이닝 세팅 연출" },
      { title: "라인업", desc: "제품 시리즈 소개" },
    ],
  },
  lacquerware: {
    type: "detail",
    title: "Lacquerware",
    desc: ["찬란한 전통의 빛", "나전칠기 명장의 작품"],
    tags: ["Detail Page", "Responsive", "Design"],
    year: "2026",
    period: "3 Weeks",
    role: "UI/UX Design, Visual Design",
    tools: ["Figma", "Photoshop"],
    overview: "전통 나전칠기의 가치와 명장의 손길을 전달하는 상세페이지입니다.",
    features: [
      { title: "명장 소개", desc: "장인의 이력과 제작 철학" },
      { title: "제작 과정", desc: "30겹 칠기·6개월 공정 시각화" },
      { title: "작품 갤러리", desc: "도자기·함·거울 등 대표 작품" },
      { title: "선물 가이드", desc: "기념일·VIP 선물 제안" },
    ],
    concept: "한지 질감과 전통 문양으로 고급 전통 공예의 품격을 표현했습니다.",
    colors: ["#1A1A1A", "#C9A227", "#F5F0E8", "#FFFFFF", "#8B4513"],
    keywords: ["Traditional", "Craft", "Luxury", "Heritage", "Gift"],
    zoom: [
      { title: "메인 비주얼", desc: "나전칠기 대표 작품" },
      { title: "명장", desc: "장인 소개와 스토리" },
      { title: "제작 과정", desc: "공정 단계별 설명" },
      { title: "후기", desc: "고객 리뷰와 만족도" },
    ],
  },
  "preservative-wood": {
    type: "detail",
    title: "Preservative Wood",
    desc: ["심플목재 방부목", "15년 품질 보증 데크"],
    tags: ["Detail Page", "Responsive", "Design"],
    year: "2026",
    period: "3 Weeks",
    role: "UI/UX Design, Visual Design",
    tools: ["Figma", "Photoshop"],
    overview: "방부목 데크의 품질과 시공 사례를 강조하는 상세페이지입니다.",
    features: [
      { title: "품질 보증", desc: "15년 무상 품질 보증 강조" },
      { title: "용도별 제품", desc: "카페·정원·놀이터 맞춤 라인업" },
      { title: "비교표", desc: "일반 목재 vs 방부목 차이" },
      { title: "시공 사례", desc: "펜션·카페 등 실제 시공 갤러리" },
    ],
    concept: "우드 톤과 자연 그린으로 친환경·내구성 이미지를 전달했습니다.",
    colors: ["#8B6914", "#D4A574", "#F5F0E8", "#FFFFFF", "#2E5C3E"],
    keywords: ["Wood", "Durable", "Natural", "Deck", "Trust"],
    zoom: [
      { title: "메인 비주얼", desc: "방부목 데크 제품" },
      { title: "품질 지표", desc: "재구매율·시공 사례 수" },
      { title: "제품 비교", desc: "일반 목재 대비 우위" },
      { title: "시공 사례", desc: "실제 설치 갤러리" },
    ],
  },
  "deo-tissue": {
    type: "detail",
    title: "Deo tissue",
    desc: ["뽀송 쿨링이 필요한 순간", "클린 뽀송 데오티슈"],
    tags: ["Detail Page", "Responsive", "Design"],
    year: "2026",
    period: "2 Weeks",
    role: "UI/UX Design, Visual Design",
    tools: ["Figma", "Photoshop"],
    overview: "여름철 땀 케어 데오티슈의 청량함을 전달하는 상세페이지입니다.",
    features: [
      { title: "쿨링 포인트", desc: "1초 산뜻·보송 효과 강조" },
      { title: "개별 포장", desc: "휴대용 개별 포장 편의성" },
      { title: "업그레이드", desc: "145만장 판매·리뉴얼 스토리" },
      { title: "사용 시나리오", desc: "운동·캠핑·출근 등 활용 장면" },
    ],
    concept: "라이트 블루와 화이트로 시원하고 깔끔한 썸머 케어 무드를 표현했습니다.",
    colors: ["#87CEEB", "#FFFFFF", "#E3F2FD", "#4FC3F7", "#FFD54F"],
    keywords: ["Cool", "Fresh", "Summer", "Portable", "Clean"],
    zoom: [
      { title: "메인 비주얼", desc: "제품과 쿨링 키워드" },
      { title: "판매 실적", desc: "145만장 판매 스토리" },
      { title: "POINT 01", desc: "개별 포장 강조" },
      { title: "POINT 02", desc: "쿨링·파우더 효과" },
    ],
  },
  sentinel: {
    type: "site",
    title: "Sentinel Aerospace",
    desc: ["우주 산업의 미래를 선도", "항공우주 기업 웹사이트"],
    tags: ["Web Site", "Responsive", "GSAP"],
    year: "2026",
    period: "5 Weeks",
    role: "UI/UX Design, Publishing, Interaction",
    tools: ["HTML", "CSS", "GSAP", "Figma"],
    overview:
      "항공우주 기업의 기술력과 비전을 전달하는 반응형 웹사이트를 기획·디자인·퍼블리싱했습니다.",
    features: [
      { title: "브랜드 아이덴티티", desc: "첨단 기술과 신뢰감을 시각적으로 표현" },
      { title: "인터랙션", desc: "GSAP 기반 스크롤 애니메이션 구현" },
      { title: "정보 구조", desc: "사업 분야별 직관적인 네비게이션" },
      { title: "반응형", desc: "PC·태블릿·모바일 최적화" },
    ],
    solution: {
      text: "기업의 전문성과 혁신 이미지를 강조하고, 방문자가 핵심 정보에 빠르게 도달하도록 설계했습니다.",
      items: [
        "다크 톤 기반의 프리미엄 비주얼",
        "스크롤 기반 스토리텔링",
        "사업 영역별 콘텐츠 구조화",
        "모션과 타이포그래피 중심 UI",
      ],
    },
    colors: ["#0A1628", "#1E3A5F", "#FFFFFF", "#4A90E2", "#F5F5F5"],
    screens: ["01. HERO", "02. 사업 소개", "03. 기술", "04. 뉴스", "05. 문의"],
  },
  "computational-platform": {
    type: "site",
    title: "Computational Platform",
    desc: ["청년 금융·계산 플랫폼", "맞춤형 금융 정보 한곳에서"],
    tags: ["Web Site", "Vibe Coding", "Responsive"],
    year: "2026",
    period: "3 Weeks",
    role: "UI/UX Design, Vibe Coding",
    tools: ["Vibe Coding", "Figma"],
    overview: "청년을 위한 금융 계산·정보 플랫폼을 Vibe Coding으로 구현했습니다.",
    features: [
      { title: "계산기 통합", desc: "대출·연봉·전월세 등 한곳에서 검색" },
      { title: "청년 정책", desc: "맞춤 혜택 정보 제공" },
      { title: "직관적 UI", desc: "검색 중심의 심플한 인터페이스" },
      { title: "반응형", desc: "모바일·데스크탑 대응" },
    ],
    solution: {
      text: "복잡한 금융 정보를 쉽게 탐색할 수 있도록 검색과 카테고리를 중심으로 설계했습니다.",
      items: [
        "일러스트 기반 친근한 비주얼",
        "검색바 중심 히어로 구성",
        "해시태그 키워드 네비게이션",
        "Vibe Coding 기반 빠른 프로토타이핑",
      ],
    },
    colors: ["#6C5CE7", "#A29BFE", "#FFFFFF", "#2D3436", "#DFE6E9"],
    screens: ["01. HERO", "02. 계산기", "03. 정책", "04. 가이드", "05. FAQ"],
  },
  taro: {
    type: "site",
    title: "Taro",
    desc: ["오늘 당신에게 찾아온 작은 행운", "따뜻한 타로 운세 서비스"],
    tags: ["Web Site", "Vibe Coding", "Responsive"],
    year: "2026",
    period: "2 Weeks",
    role: "UI/UX Design, Vibe Coding",
    tools: ["Vibe Coding", "Figma"],
    overview: "일상 속 작은 행운을 전하는 타로 운세 웹 서비스를 Vibe Coding으로 제작했습니다.",
    features: [
      { title: "감성 UI", desc: "다크 톤과 골드 포인트의 신비로운 무드" },
      { title: "오늘의 카드", desc: "데일리 타로 뽑기 기능" },
      { title: "퀵 메뉴", desc: "원하는 운세를 바로 시작" },
      { title: "반응형", desc: "모바일 퍼스트 레이아웃" },
    ],
    solution: {
      text: "타로의 신비로움과 접근성을 동시에 전달하는 따뜻한 다크 테마 UI를 설계했습니다.",
      items: [
        "타로 카드 일러스트 중심 비주얼",
        "직관적인 퀵 메뉴 구조",
        "감성적인 타이포그래피",
        "Vibe Coding 기반 인터랙션",
      ],
    },
    colors: ["#1A1A2E", "#C9A227", "#FFFFFF", "#16213E", "#E8D5A3"],
    screens: ["01. HERO", "02. 오늘의 카드", "03. 리딩", "04. 북", "05. 마이"],
  },
  bebetree: {
    type: "site",
    title: "Bebe Tree",
    desc: ["초보 부모를 위한 육아 정보", "월령·이유식·놀이 한곳에서"],
    tags: ["Web Site", "Vibe Coding", "Responsive"],
    year: "2026",
    period: "3 Weeks",
    role: "UI/UX Design, Vibe Coding",
    tools: ["Vibe Coding", "Figma"],
    overview: "초보 부모를 위한 육아 정보 플랫폼을 Vibe Coding으로 구현했습니다.",
    features: [
      { title: "육아 가이드", desc: "월령별 맞춤 정보 제공" },
      { title: "이유식·식단", desc: "단계별 식단 가이드" },
      { title: "놀이·교육", desc: "발달 단계별 활동 제안" },
      { title: "육아 계산기", desc: "편리한 도구 모음" },
    ],
    solution: {
      text: "부모가 필요한 정보를 빠르게 찾을 수 있도록 카테고리와 검색을 중심으로 구성했습니다.",
      items: [
        "따뜻한 파스텔 톤 비주얼",
        "드롭다운 메뉴 기반 탐색",
        "3D 일러스트 감성",
        "Vibe Coding 기반 구현",
      ],
    },
    colors: ["#FFB6C1", "#98D8C8", "#FFFFFF", "#FFD93D", "#6B4C7A"],
    screens: ["01. HERO", "02. 가이드", "03. 이유식", "04. 놀이", "05. 계산기"],
  },
  cheongyeon: {
    type: "site",
    title: "Cheongyeon",
    desc: ["청년을 위한 금융 플랫폼", "팀 프로젝트"],
    tags: ["Team Project", "React", "TypeScript"],
    year: "2026",
    period: "8 Weeks",
    role: "UI/UX Design, Front-end Development",
    team: "2 People",
    tools: ["React", "TypeScript", "Figma"],
    overview: "청년 금융 서비스를 팀으로 기획·디자인·개발한 프로젝트입니다.",
    features: [
      { title: "팀 협업", desc: "디자인·개발 역할 분담과 협업" },
      { title: "React SPA", desc: "컴포넌트 기반 프론트엔드 구현" },
      { title: "금융 UX", desc: "복잡한 정보의 단순화" },
      { title: "반응형", desc: "다양한 디바이스 대응" },
    ],
    solution: {
      text: "팀원 간 디자인 시스템과 코드 컨벤션을 공유하며 일관된 사용자 경험을 구축했습니다.",
      items: [
        "Figma 기반 디자인 시스템",
        "React + TypeScript 아키텍처",
        "컴포넌트 재사용성 확보",
        "스프린트 기반 애자일 진행",
      ],
    },
    colors: ["#6C5CE7", "#FFFFFF", "#2D3436", "#A29BFE", "#DFE6E9"],
    screens: ["01. HERO", "02. 서비스", "03. 기능", "04. 대시보드", "05. 문의"],
  },
  poppi: {
    type: "site",
    title: "Poppi Donuts",
    desc: ["DONUT WORRY, BE POPPI", "프리미엄 도넛 브랜드"],
    tags: ["Team Project", "React", "TypeScript"],
    year: "2026",
    period: "6 Weeks",
    role: "UI/UX Design, Front-end Development",
    team: "2 People",
    tools: ["React", "TypeScript", "Figma"],
    overview: "도넛 브랜드 웹사이트를 팀으로 기획·디자인·개발한 프로젝트입니다.",
    features: [
      { title: "브랜드 무드", desc: "플레이풀한 컬러와 일러스트" },
      { title: "제품 소개", desc: "도넛 라인업과 스토리텔링" },
      { title: "팀 협업", desc: "디자인-개발 긴밀한 소통" },
      { title: "반응형", desc: "모바일 쇼핑 경험 최적화" },
    ],
    solution: {
      text: "브랜드의 유쾌한 개성을 웹에 담고, 제품 탐색에서 주문까지 자연스러운 흐름을 설계했습니다.",
      items: [
        "오렌지·핑크 브랜드 컬러",
        "일러스트 기반 히어로",
        "React 컴포넌트 구조",
        "팀 코드 리뷰 프로세스",
      ],
    },
    colors: ["#F27435", "#F48FB1", "#FFFFFF", "#3D2817", "#FFF8E7"],
    screens: ["01. HERO", "02. 메뉴", "03. 스토리", "04. 매장", "05. 주문"],
  },
};
